jobs:
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo
    steps:
      - checkout

      - run: npm install
      - run: npm run build
      - run:
          name: test
          command: |
            export APPLITOOLS_BATCH_ID=$CIRCLE_SHA1
            export APPLITOOLS_BRANCH_NAME=$CIRCLE_BRANCH
            npm test
